nameOverride: ""
fullnameOverride: ""
image:
  cnosdb:
    repository: cnosdb/cnosdb
    tag: community-latest
  clusterConfTool:
    repository: wyxok/cnosdb-init-config
    tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

# Allowed values: `singleton` or `cluster` 优先实现cluster， singleton先不实现
architecture: cluster
meta:
  replicaCount: 3
  terminationGracePeriodSeconds: 10
  # 这里可以自定义配置去覆盖默认配置
  extraConf: {}
  resources:
    limits: {}
    requests: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    port: 8901
    nodePort: ""
    clusterIP: ""
    externalTrafficPolicy: Cluster
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  persistence:
    enabled: false
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    existingClaim: ""
tskv:
  replicaCount: 2
  terminationGracePeriodSeconds: 10
  extraConf: {}
  resources:
    limits: {}
    requests: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    ports:
      http: 8902
      grpc: 8903
      flight: 8904
      tcp: 8905
    nodePorts:
      http: ""
      grpc: ""
      flight: ""
      tcp: ""
    clusterIP: ""
    externalTrafficPolicy: Cluster
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  persistence:
    enabled: false
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    existingClaim: ""
query:
  replicaCount: 2
  extraConf: {}
  resources:
    limits: {}
    requests: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    ports:
      http: 8902
      flight: 8904
    nodePorts:
      http: ""
      flight: ""
    clusterIP: ""
    externalTrafficPolicy: Cluster
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
##todo##
## If queryTskv is enable, query and tskv would be disabled
queryTskv:
  enbale: false
  replicaCount: 2
  terminationGracePeriodSeconds: 10
  extraConf: {}
  resources:
    limits: {}
    requests: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  service:
    type: ClusterIP
    ports:
      http: 8902
      grpc: 8903
      flight: 8904
      tcp: 8905
    nodePorts:
      http: ""
      grpc: ""
      flight: ""
      tcp: ""
    clusterIP: ""
    externalTrafficPolicy: Cluster
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  persistence:
    enabled: false
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 500Mi
    existingClaim: ""
