{{- if not (empty .Values.license) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cnosdb.fullname" . -}}-license
  labels:
    cnosdb.com/app: cnosdb
    cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}
    {{- include "cnosdb.labels" . | nindent 4 }}
data:
  license: |
    {{- .Values.license | nindent 4 }}
{{- end }}