apiVersion: v1
kind: Service
metadata:
  name: {{ include "cnosdb.fullname" . -}}-query-svc
  labels:
    cnosdb.com/app: cnosdb
    cnosdb.com/role: query
    cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}
    {{- include "cnosdb.labels" . | nindent 4 }}
  {{- if  .Values.query.service.annotations }}
  annotations: {{- include "cnosdb.toYaml" ( dict "value" .Values.query.service.annotations ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.query.service.type }}
  {{- if and .Values.query.service.clusterIP (eq .Values.query.service.type "ClusterIP") }}
  clusterIP: {{ .Values.query.service.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.query.service.type "LoadBalancer") (eq .Values.query.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.query.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.query.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.query.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if (and (eq .Values.query.service.type "LoadBalancer") (not (empty .Values.query.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.query.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.query.service.ports.http }}
      targetPort: http
      name: http
      {{- if and (or (eq .Values.query.service.type "NodePort") (eq .Values.query.service.type "LoadBalancer")) .Values.query.service.nodePorts.http }}
      nodePort: {{ .Values.query.service.nodePorts.http }}
      {{- end }}
    - port: {{ .Values.query.service.ports.grpc }}
      targetPort: grpc
      name: grpc
      {{- if and (or (eq .Values.query.service.type "NodePort") (eq .Values.query.service.type "LoadBalancer")) .Values.query.service.nodePorts.grpc }}
      nodePort: {{ .Values.query.service.nodePorts.grpc }}
      {{- end }}
    - port: {{ .Values.query.service.ports.flight }}
      targetPort: flight
      name: flight
      {{- if and (or (eq .Values.query.service.type "NodePort") (eq .Values.query.service.type "LoadBalancer")) .Values.query.service.nodePorts.flight }}
      nodePort: {{ .Values.query.service.nodePorts.flight }}
      {{- end }}
    - port: {{ .Values.query.service.ports.tcp }}
      targetPort: tcp
      name: tcp
      {{- if and (or (eq .Values.query.service.type "NodePort") (eq .Values.query.service.type "LoadBalancer")) .Values.query.service.nodePorts.tcp }}
      nodePort: {{ .Values.query.service.nodePorts.tcp }}
      {{- end }}
    - port: {{ .Values.query.service.ports.vector }}
      targetPort: vector
      name: vector
      {{- if and (or (eq .Values.query.service.type "NodePort") (eq .Values.query.service.type "LoadBalancer")) .Values.query.service.nodePorts.vector }}
      nodePort: {{ .Values.query.service.nodePorts.vector }}
      {{- end }}
  selector:
    cnosdb.com/app: cnosdb
    cnosdb.com/role: query
    cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}
