apiVersion: v1
kind: Service
metadata:
  name: {{ include "cnosdb.fullname" . -}}-tskv
  labels:
    cnosdb.com/app: cnosdb
    cnosdb.com/role: tskv
    cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}
    {{- include "cnosdb.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8902
      name: http
    - port: 8903
      name: grpc
    - port: 8904
      name: flight
    - port: 8905
      name: tcp
    - port: 8906
      name: vector
  clusterIP: None
  selector:
    cnosdb.com/app: cnosdb
    cnosdb.com/role: tskv
    cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}