{{- if eq .Values.architecture "bundle" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cnosdb.fullname" . -}}-querytskv
  labels:
    cnosdb.com/app: cnosdb
    cnosdb.com/role: query_tskv
    cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}
    {{- include "cnosdb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      cnosdb.com/app: cnosdb
      cnosdb.com/role: query_tskv
      cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}
  serviceName: "{{ include "cnosdb.fullname" . -}}-querytskv"
  podManagementPolicy: Parallel
  replicas: {{ .Values.queryTskv.replicaCount }}
  template:
    metadata:
      labels:
        cnosdb.com/app: cnosdb
        cnosdb.com/role: query_tskv
        cnosdb.com/cluster: {{ include "cnosdb.fullname" . }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.queryTskv.terminationGracePeriodSeconds }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.queryTskv.affinity }}
      affinity: {{- include "cnosdb.toYaml" (dict "value" .Values.queryTskv.affinity ) | nindent 8 }}
      {{- end }}
      {{- if .Values.queryTskv.nodeSelector }}
      nodeSelector: {{- include "cnosdb.toYaml" (dict "value" .Values.queryTskv.nodeSelector ) | nindent 8 }}
      {{- end }}
      {{- if .Values.queryTskv.tolerations }}
      tolerations: {{- include "cnosdb.toYaml" (dict "value" .Values.queryTskv.tolerations ) | nindent 8 }}
      {{- end }}
      initContainers:
        - name: fetch-conf
          image: "{{ .Values.image.cnosdb.repository }}:{{ .Values.image.cnosdb.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["cp","/etc/cnosdb/cnosdb.conf","/etc/initconf/default.conf"]
          volumeMounts:
            - name: config
              mountPath: "/etc/initconf"
        - name: init-conf
          image: "{{ .Values.image.clusterConfTool.repository }}:{{ .Values.image.clusterConfTool.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CNOSDB_ROLE
              value: query_tskv
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: META_SVC_NAME
              value: {{ include "cnosdb.fullname" . -}}-meta
            - name: META_SVC_PORT
              value: "8901"
            - name: META_STS_NAME
              value: {{ include "cnosdb.fullname" . -}}-meta
            - name: META_REPLICAS
              value: "{{ .Values.meta.replicaCount }}"
            - name: SVC_NAME
              value: {{ include "cnosdb.fullname" . -}}-querytskv
            - name: CLUSTER_INSTANCE_NAME
              value: {{ include "cnosdb.fullname" . }}
            - name: CONF_FROM_USER
              value: '{{ include "cnosdb.extraConfig" (dict "value" .Values "conf" .Values.queryTskv.extraConf) }}'
          args: ["-type", "conf"]
          volumeMounts:
            - name: config
              mountPath: "/etc/initconf"
      containers:
        - name: cnosdb-querytskv
          image: "{{ .Values.image.cnosdb.repository }}:{{ .Values.image.cnosdb.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              cnosdb run -M query_tskv --config /etc/cnosdb/cnosdb.conf
          ports:
            - containerPort: 8902
              name: http
            - containerPort: 8903
              name: grpc
            - containerPort: 8904
              name: flight
            - containerPort: 8905
              name: tcp
            - containerPort: 8906
              name: vector
          {{- if .Values.queryTskv.resources }}
          resources: {{- toYaml .Values.queryTskv.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/etc/cnosdb"
            - name: querytskv-data
              mountPath: "/var/lib/cnosdb"
            {{- if not (empty .Values.license) }}
            - name: license
              mountPath: "{{ .Values.licensePath | trimSuffix "/" }}/license.json"
              subPath: "license.json"
            {{- end }}
      volumes:
        - name: config
          emptyDir: {}
      {{- if not (empty .Values.license) }}
        - configMap:
            items:
            - key: license
              path: license.json
            name: {{ include "cnosdb.fullname" . -}}-license
          name: license
      {{- end }}
  {{- if not .Values.queryTskv.persistence.enabled }}
        - name: querytskv-data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: querytskv-data
      spec:
        accessModes:
        {{- range .Values.queryTskv.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.queryTskv.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.queryTskv.persistence.size | quote }}
  {{- end }}
{{- end }}